### ISSUE TITLE
Thank you so much!

### ISSUE THREAD

**Issue by mikemeixner** [flyinggorilla/whisper-foiling-catamaran#1]
Hello and thank you for all the info you posted regarding the Whisper. I also own a Whisper and found the information you provide very useful. I recently lost a wand and used your 3D files to print the paddle and wand arm. I'm currently looking for a distributor for the CF 8mm rods that are willing to ship to Canada. 

![IMG_0244](https://github.com/flyinggorilla/whisper-foiling-catamaran/assets/73126172/4e403ab2-9924-491e-8f48-85494398277f)

**Comment by flyinggorilla** [comment]
Awesome! 

Just one suggestion, in case you find the wand arm breaking. As to your picture, the print was dont from the rod-opening upwards to the bungee hole. this causes most force to be held by 3D print interlayer adhesion, what is the weak spot of FFF 3D printing. So if you find it is breaking, I suggest to print it layed down with supports. It works with support of same material (and using a drill and pliers to remove supports) or dissolvable support. When you lay down the wand arm, the forces are in direction of extruded material, what makes it stronger.
